name: Update README Timestamp

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update README.md with current time
        run: |
          current_time=$(date -u "+%Y-%m-%d %H:%M:%S UTC")
          
          sed -i "s|{{PLACEHOLDER_TIMESTAMP}}|$current_time|g" README.md

      - name: Commit and Push Changes
        run: |
          git config --local user.name "${{ secrets.GIT_NAME}}"
          git config --local user.email "${{ secrets.GIT_EMAIL}}"

          git add README.md
          git commit -m "Update README timestamp to $current_time" || echo "No changes to commit"
          
          git push
