name: Update README Timestamp

on:
  schedule:
    - cron: "* * * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update README.md with current time (Jakarta)
        run: |
          current_time=$(TZ="Asia/Jakarta" date "+%Y-%m-%d %H:%M:%S")

          sed -i 's|<!--TIMESTAMP-->.*<!--TIMESTAMP_END-->|<!--TIMESTAMP-->'"$current_time"'<!--TIMESTAMP_END-->|g' README.md

      - name: Commit and Push Changes
        run: |
          git config --local user.name "${{ secrets.GIT_NAME}}"
          git config --local user.email "${{ secrets.GIT_EMAIL}}"

          git add README.md
          git commit -m "Update README timestamp to $current_time" || echo "No changes to commit"
          
          git push
